name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      working-directory: ./WIFI_PC/WIFI_PC
      run: dotnet restore
    
    - name: Build
      working-directory: ./WIFI_PC/WIFI_PC
      run: dotnet build --no-restore --configuration Release
    
    - name: Publish
      working-directory: ./WIFI_PC/WIFI_PC
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          RUNTIME=win-x64
        elif [ "$RUNNER_OS" == "Linux" ]; then
          RUNTIME=linux-x64
        elif [ "$RUNNER_OS" == "macOS" ]; then
          RUNTIME=osx-x64
        fi
        dotnet publish --no-build --configuration Release --runtime $RUNTIME --output ./publish/$RUNTIME